#!/bin/bash

echo "WordPress Post-Installation Commands"
echo "===================================="
echo ""
echo "After WordPress installation, run these commands:"
echo ""
echo "1. Install WP-CLI (WordPress command line):"
echo "   curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
echo "   chmod +x wp-cli.phar"
echo "   sudo mv wp-cli.phar /usr/local/bin/wp"
echo ""
echo "2. Activate theme:"
echo "   wp theme activate skerritt-economics"
echo ""
echo "3. Install plugins:"
echo "   wp plugin install contact-form-7 --activate"
echo "   wp plugin install wordpress-seo --activate"
echo "   wp plugin install updraftplus --activate"
echo "   wp plugin install wordfence --activate"
echo ""
echo "4. Configure permalinks:"
echo "   wp rewrite structure '/%postname%/'"
echo "   wp rewrite flush"
echo ""
echo "5. Set homepage:"
echo "   wp option update show_on_front 'page'"
echo "   wp option update page_on_front \$(wp post list --post_type=page --name=home --field=ID)"
echo ""
echo "6. Create menus:"
echo "   wp menu create 'Primary Menu'"
echo "   wp menu location assign 'Primary Menu' primary"
echo ""
echo "Or do these steps manually in the WordPress admin panel."